const DataOfPoints = [
    { src: './images/RedPoint.jpg' },
    { src: './images/RedPoint.jpg' },
    { src: '' },
    { src: './images/RedPoint.jpg' },
    { src: '' },
    { src: '' },
    { src: './images/BluePoint.jpg' },
    { src: '' },
    { src: '' },
    { src: '' },
    { src: './images/RedPoint.jpg' },
    { src: '' },
    { src: '' },
    { src: './images/BluePoint.jpg' },
    { src: './images/BluePoint.jpg' },
    { src: './images/BluePoint.jpg' },
    { src: '' },
    { src: '' },
    { src: '' },
    { src: '' },
    { src: './images/RedPoint.jpg' },
    { src: '' },
    { src: './images/BluePoint.jpg' },
    { src: '' },
    { src: '' },
];
export default DataOfPoints;